### ISSUE TITLE
Not working with office 365

### ISSUE THREAD

**Issue by gauravbhavsar** [rse/slideshow#13]
I am trying to open and run PPT presentation using commands, but getting error on open file command,

>Unhandled rejection application still not running

![ppt](https://user-images.githubusercontent.com/5441386/43988933-152ba11a-9d5e-11e8-9348-a47e086fce7c.png)

Thanks,

**Comment by Ebbez** [comment]
Hi, have you found any solution to this problem? I am facing the same problem right now.

**Comment by gauravbhavsar** [comment]
Please look into the package `slideshow` inside node_modules, you will find the supported connectors and they are 
* win32-powerpoint
* win32-powerpoint2010
* win32-powerpoint2013

for other versions, you can do modify the `connector-win-ppt2010.js` file.

**Comment by wgrhstf** [comment]
Can you go a bit more into Detail how you managed to to change the `connector-win-ppt2010.js` to work with office 365? 
I'm not able to find out why the error occurs.
