### ISSUE TITLE
Get info about current state

### ISSUE THREAD

**Issue by guillaumepotier** [rse/slideshow#3]
Hi there,

Currently if I'm not mistaking, it is possible to call `info` to have info about the general presentation. But is it possible to obtain info about current state, ie on which slide we are, how many next actions before next slide, etc, etc..

Otherwise, great lib!

Best

**Comment by rse** [comment]
The "stat" command gives you the current slide position and the maximum number of slides. I think this should be what you want.

**Comment by guillaumepotier** [comment]
Oh great, missed that one. Thx
