### ISSUE TITLE
How would I go about telling it to go "next slide" on an already open presentation?

### ISSUE THREAD

**Issue by JohnMcLear** [rse/slideshow#6]

**Comment by rse** [comment]
There is a .next() method. See slideshow-api.js for details on all methods. Sorry that they are not documented in the README until now...

**Comment by JohnMcLear** [comment]
All examples show the module being used to open a presentation first.  I assume that this isn't the case?  Apologies I can't test this here so having to develop blind -_-

**Comment by rse** [comment]
It should also work with an already open presentation, although I cannot test it myself currently, too.
